name = "synttx/scythe"
version = "1.2.1"
description = "A Data-Oriented Cleanup Library · Up to ×17 lighter than other maids"
authors = ["synttx <synttx@proton.me>"]
license = "MPL-2.0"
repository = "https://github.com/synttx/oss/tree/main/packages/scythe"

includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/**",
]

[target]
environment = "roblox"
lib = "src/scythe.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"
