[package]
name = "synttx/scythe"
version = "1.2.1"
description = "A Data-Oriented Cleanup Library · Up to ×17 lighter than other maids"
authors = ["synttx <synttx@proton.me>"]
realm = "shared"
license = "MPL-2.0"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/synttx/oss/tree/main/scythe"
keywords = ["janitor", "maid", "cleanup", "trove"]
exclude = [
    "assets",
    "benchmarks",
]

[dependencies]
